// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Todo struct {
	ID       int32        `json:"id"`
	Name     string       `json:"name"`
	IsCheck  bool         `json:"is_check"`
	CreateAt sql.NullTime `json:"create_at"`
}
