// Code generated by sqlc. DO NOT EDIT.
// source: todos.sql

package db

import (
	"context"
)

const listTodos = `-- name: ListTodos :many
select id, name, is_check, create_at from todos
`

func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.query(ctx, q.listTodosStmt, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsCheck,
			&i.CreateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTodo = `-- name: SetTodo :exec
insert into todos(name)values($1)
`

func (q *Queries) SetTodo(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.setTodoStmt, setTodo, name)
	return err
}
